site_name: Instalación de programas
site_url: https://github.com/enriquegreri/u1_a4_enrique_gregori_ribera-/
docs_dir: 'md'
site_dir: 'docs'
repo_url: https://github.com/enriquegreri/u1_a4_enrique_gregori_ribera-/
repo_name: enriquegreri/u1_a4_enrique_gregori_ribera-
edit_uri: 'https://github.com/enriquegreri/u1_a4_enrique_gregori_ribera-/blob/main/md/'
hide:
  - navigation
  - toc
nav:
    - Web Para instalar programas:
      - Luckybackups: luckybackup.md
      - Gimp: gimp.md
plugins: []
theme:
  logo: img/favicon.ico
  name: material
  font:
    text: Ubuntu
  palette: 
      scheme: slate
      primary: deep orange
      accent: white
  favicon: img/favicon.ico
  features:
    - toc.follow
    - toc.integrate
    - search.suggest

